### ISSUE TITLE
How to set the data for training?

### ISSUE THREAD

**Issue by limberc** [HanGuo97/soft-Q-learning-for-text-generation#2]
Hi there, thanks for this amazing works!

However, I am still confusing about the data setup part.

According to the `configs/data` setup. For SNLI task, we have got the following setup:

```
base_path = "/export/share/Data/snli/entailment"
max_source_length = 100
max_decoding_length = 50

source_vocab_file = os.path.join(base_path, "vocab.None")
target_vocab_file = os.path.join(base_path, "vocab.None")
val_unique_pairs_file = os.path.join(base_path, "validation-unique.pairs.unique.pth")
test_unique_pairs_file = os.path.join(base_path, "test-unique.pairs.unique.pth")

```

I am not sure about what the `base_path` is when we using the Hugginface Datasets lib. 

I am using the `load_dataset` to download the dataset, and found that the folder structure is:

```
├── dataset_info.json
├── LICENSE
├── snli-test.arrow
├── snli-train.arrow
└── snli-validation.arrow
```

In this case, I think the setup does not fit your config's setup. Can you present the detailed setup for how to use Huggingface dataset to fit the setup?

**Comment by HanGuo97** [comment]
Hi, unfortunately, we do not (directly) support using `datasets`, and you have to preprocess the data into line-by-line examples. It's very straightforward, though.

Below I have attached the dataset you mentioned above as a reference -- hope it's helpful!

[snli-entailment.zip](https://github.com/HanGuo97/soft-Q-learning-for-text-generation/files/6777597/snli-entailment.zip)
