### ISSUE TITLE
Pretrained GPT2 model encoder

### ISSUE THREAD

**Issue by xingweiqu** [HanGuo97/soft-Q-learning-for-text-generation#3]
Hi, thanks for your amazing work. 

However, I am confused at the training setting for gpt2 model set-up.

```
  MAX_SEQ_LENGTH = 128
    MODEL_NAME = "gpt2-small"
    CACHE_DIR = "/export/share/Experiments/20210517/gpt2-models/"
    CKPT_PATHS = {
        "snli": "/export/share/Experiments/20210518/gpt2_snli/model.ckpt",
        "multinli": "/export/share/Experiments/20210518/gpt2_multinli/model.ckpt",
    }
```

It seems that we are use the pretrained GPT2 model for Snli and Multnli task. Could you offer the gpt2-model dir for me to reproduce the result?

**Comment by HanGuo97** [comment]
Hi, thanks for being interested in the work! TLDR, they are GPT-2 models fine-tuned on the corresponding datasets. [Here](https://drive.google.com/file/d/1ekAQbN1k0nNbB5OURMn112uJIThhk6i0/view?usp=sharing) are the files you are looking for.

Putting them in the right directory should work. However, I remember having to change `texar` source code a bit at one point, either for training or inference. They are simple changes nonetheless. So I'd keep that in mind in case you ever run into strange issues (hopefully not!).
