### ISSUE TITLE
是否可以结合实际场景给些使用例子

### ISSUE THREAD

**Issue by liangwq** [HanGuo97/soft-Q-learning-for-text-generation#4]
用强化学习来加速条件控制下的文本生成是个很不错的思路
把大模型当成是agent，
用户的各种文本控制条件作为环境
但是感觉这是个框架性工具，没有例子其实大众很难去用这个东西

**Comment by HanGuo97** [comment]
Hi, thanks for being interested in this project and asking this great question.

We just uploaded our latest work (https://arxiv.org/abs/2205.12548) to arXiv, and hope this would be helpful!
