### ISSUE TITLE
Prompt experiment data setup

### ISSUE THREAD

**Issue by masoudhashemi** [HanGuo97/soft-Q-learning-for-text-generation#5]
Hi, thanks for sharing the code for this amazing work. 

I am trying to run the prompt experiment, but cannot figure out the data setup. Could you please help me to create the needed data inputs (configs/data/prompt/gpt2_mixed.py)?

Thanks!

**Comment by HanGuo97** [comment]
Hi, thanks for being interested! Please check out [this](https://github.com/HanGuo97/soft-Q-learning-for-text-generation/issues/1). Somewhat related, we also have a [follow-up work](https://github.com/mingkaid/rl-prompt) with better documentation.

Hope these help!

**Comment by masoudhashemi** [comment]
Thanks a lot! it helped. 
Thanks for introducing the other paper too.
