### ISSUE TITLE
Understanding the loss function soft_q_loss_with_sparse_rewards_3

### ISSUE THREAD

**Issue by cyndaq** [HanGuo97/soft-Q-learning-for-text-generation#6]
Hi,
Thanks a lot for such a promising work. I really appreciate making the code so readily available.
I am trying to use the proposed method for a spelling correction task. 

Please correct me if I'm wrong-
To the best of my understanding the loss function soft_q_loss_with_sparse_rewards_3 is the implemetation of the MultiStep PCL-SQL objective (Equation 11 in the paper). However, I found that the implementation does not include the discount factor gamma.

I was curious about this. Is this by design that we do not discount the rewards (gamma == 1)?

**Comment by HanGuo97** [comment]
Hi, thanks for being interested in this work!

Great question. We did not include the discount factor (which is usual in language generation tasks). The formulation, however, is indifferent to this choice. I remember all you need is to put coefficients somewhere to make it work.
