### ISSUE TITLE
Updating of requirements.txt

### ISSUE THREAD

**Issue by quaterhalfbro** [HanGuo97/soft-Q-learning-for-text-generation#7]
Hi!
requirements.txt does not contain versions, a conflict occurs during loading. Also requirements from GEM-metrics are missing.
Here is my working requirements for this project:

wandb==0.13.2
matplotlib==3.5.3
pandas==1.4.4
click==7.1.2
graphviz==0.20.1
transformers==4.21.3
spacy==3.4.1
datasets==2.4.0
sacrebleu==2.2.0
numpy==1.22.0
joblib==1.1.0
nltk==3.7
tqdm==4.64.1
omegaconf==2.0.6
regex==2022.8.17
sentencepiece==0.1.97
six==1.16.0
scipy==1.9.1
setuptools==65.3.0
pytorch_lightning==1.7.5
bert_score
rouge-score
logzero==1.7.0
pycountry==22.3.5
git+https://github.com/google-research/bleurt.git
git+https://github.com/recitalAI/QuestEval.git@gem#egg=questeval
sacremoses==0.0.53
nubia-score
texar==0.2.1
fairseq==0.12.2
pathlib==1.0.1
funcsigs==1.0.2
tensorflow==2.10.0
torch==1.12.1

**Comment by HanGuo97** [comment]
Thanks for the effort! (The GEM dependency was included elsewhere.)
