### ISSUE TITLE
GEM-metrics version update is missing

### ISSUE THREAD

**Issue by featherrrrrr** [HanGuo97/soft-Q-learning-for-text-generation#8]
Hello,
The GEM-metrics version 2693f3439547a40897bc30c2ab70e27e992883c0 you are using has no relevant content (or has been updated). Could you please post the previous version of the file?

**Comment by HanGuo97** [comment]
Hi, thanks for reaching out!

I would just give the latest version a try and see if it works. Note that there could be conflicting dependencies.
